### ISSUE TITLE
Requirements repeater not adding new fields

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#10]
I edit a download and hit the Add button for making new requirements but nothing occurs.

**Comment by d4mation** [comment]
Turns out that this is due to RBM Field Helpers being loaded as a mu-plugin over Multisite. The resources aren't loading correctly.

I'll have to do a quick commit for that Plugin to make it properly support being loaded as a regular Plugin or otherwise get it to load differently.

**Comment by d4mation** [comment]
Just uploaded a fix to the Server. This same Issue seems to have also caused #9. Before I fixed this I was able to reproduce #9, but now I can't.
