### ISSUE TITLE
Max width on download single feature areas

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#12]
Looks like requirements, testimonials, etc. do not have a max width defined. Text is hard against the window edge.

**Comment by d4mation** [comment]
Their containers are full-width so the color extends to the edge of the page, but any content is within a `row` class to keep them off the edges. That's really weird.

Are you using Chrome? This might be a tricky one to nail down.

![image](https://cloud.githubusercontent.com/assets/7770631/17228969/6723b162-54e3-11e6-8bc0-18ad098d5977.png)

**Comment by brashrebel** [comment]
Yes, I'm in Chrome. Everything except the plugin description section is full width for me. I don't see what is in your screenshot.

**Comment by brashrebel** [comment]
Other pages like Hire Us are also full width for me.

**Comment by d4mation** [comment]
What resolution is the screen you're using? It seems to happen at some weird breakpoints.

![image](https://cloud.githubusercontent.com/assets/7770631/17249224/fddfd156-556c-11e6-8fb8-7e8a4da6fa24.png)

**Comment by brashrebel** [comment]
If I zoom way out in my browser, I can get it to set a max width. Otherwise at like 956px wide, it's hard against the window edge. Same on pages too.

**Comment by d4mation** [comment]
Yep, looks like it is a problem at around 800-1000px wide. I'm used to more like 2000px wide and it doesn't seem to be present on Mobile which is why I missed it.

I've got a fix on the way, I just need to apply it to all the sections and ensure it is good on every page. 👍

**Comment by d4mation** [comment]
It looks better on my end now. Although I couldn't replicate your issue on the Hire Us Page...

![image](https://cloud.githubusercontent.com/assets/7770631/17250662/620ab87a-5573-11e6-9106-dd2109e5f273.png)

**Comment by d4mation** [comment]
Could you send me a screenshot of how the Hire Us page looks for you?

**Comment by brashrebel** [comment]
Ok, now I have a little more padding on the download single sections. And on the pages. But they're still... pretty wide.

**Comment by d4mation** [comment]
I've adjusted the way the Padding works now to mirror how most of our client sites work. Now there's a minimum of `30px` padding on any given element from the edges.

How does it look on your end?

![image](https://cloud.githubusercontent.com/assets/7770631/17253142/74de912e-557d-11e6-9e49-ef1aa319daaa.png)

**Comment by brashrebel** [comment]
Good for me.
