### ISSUE TITLE
Create some type of left right boundary for content on 1080p or higher monitors

### ISSUE THREAD

**Issue by BigActual** [realbigplugins/theme2016#26]
Per Kyle's reference in #24  and my observations, I think that the content looks disorganized at full width on 1080p or larger screens for Download Items. I recommend that these larger displays have a max available width for content. 

There are some items which I like on the page at full width however:
- Hero image on the home page
- Main Menu and Footer background graphics
- Testimonials on the Download Items

Acknowledging the beauty of those items leads me to a desire to just have "Content" controlled at width that currently has a white background. Now that doesn't mean that I think we should add colors to the background of existing elements and call it good. Conversely, I believe we should just limit the width of the "content elements", unless they are similar to the testimonials where there are two side by side. Something akin to the width of our support page content.

**Comment by d4mation** [comment]
The Archive and Single templates for Downloads will be very different with #39 which should be merged in soon 👍
