### ISSUE TITLE
Purchase history tables unstyled

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#31]
The EDD purchase history tables look terrible right now. We need to spruce them up ASAP.

**Comment by d4mation** [comment]
Aside from some spacing between the Subscriptions and the table it looks fairly standard for a table to me.

Is there something particular you have in mind for making it better? Aside from some branding colors and/or removing that gray box around the headers and making it simply an underline I can't think of much. Tables tend to have a distinct look about them.

![image](https://cloud.githubusercontent.com/assets/7770631/18953994/018bb86e-861f-11e6-9098-9a8fb9549ff2.png)

**Comment by brashrebel** [comment]
I should have been more specific. Click on the links.

**Comment by d4mation** [comment]
Ah, yep. That's no good. I'll address this sometime soon.

**Comment by d4mation** [comment]
Simple changes, made a huge difference. (This is a test purchase I made while testing that e-mail stuff yesterday).

![image](https://cloud.githubusercontent.com/assets/7770631/19075401/c2387cae-8a12-11e6-9261-b8a1c000227e.png)

**Comment by joelworsham** [comment]
:heart_eyes:
