### ISSUE TITLE
Stripped down checkout page

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#32]
Some other product company owners have discovered taking measures to drastically simplify the checkout page has a noteworthy impact on conversions. Here's what I want to try.

On the checkout page let's eliminate everything. Ditch the footer completely and make the header show nothing but the Real Big Plugins logo. Let's strip out anything we can.

**Comment by d4mation** [comment]
We can do that, but it sounds non-userfriendly to me. It seems like it would drive up conversions by making navigating away from the page less convenient.

**Comment by brashrebel** [comment]
Yeah, exactly. It works.
