### ISSUE TITLE
Footer Enhancements

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/theme2016#41]
Copying everything here for my convenience

![image](https://cloud.githubusercontent.com/assets/7770631/19536485/227b232e-961a-11e6-961c-bbc72a75a25c.png)

> Also, the email input field should probably be put in there right next to the subscribe button in the footer.

> I had anticipated the link taking the user to a signup form generated from MailChimp. Seems easier that way to me. Any downsides I'm not aware of?

> As for the opt in form in the footer, I think I'd rather have the field right there, just to the left of the button. No reason to send a user to a page off of our site if we don't have to.

> If you'd like the field there, sure thing. They will be directed to another page either way won't they? The mailchipm message "confirm in your email blah blah"

> We can show that message inline if we want. User does not have to go to another page and we definitely don't want them to.

**Comment by joelworsham** [comment]
One other thing is that the "Helpful Links" really only applies to the logged in user. So perhaps there should be something else there for people not logged in?

**Comment by d4mation** [comment]
Cart and Checkout I believe still function if you aren't logged in as you are forced to log in or create an account as part of the Checkout process.

Account though, yeah, probably right. Unless it gives you a login/registration screen.

**Comment by joelworsham** [comment]
Ah yes true.
