### ISSUE TITLE
Archive 2 column not aligning properly

### ISSUE THREAD

**Issue by joelworsham** [realbigplugins/theme2016#47]
http://d.pr/i/ecpo

I would advise making the plugins a `<ul>` and using the "block-grid" from Foundation. It does a pretty great job at this kind of scenario.

**Comment by d4mation** [comment]
[It looks like Block Grid was merged into the Main Grid in Foundation 6](https://foundation.zurb.com/sites/docs/grid.html#block-grids)

I'll play with this and see what I can come up with.

**Comment by joelworsham** [comment]
Ah yes that's right. So you assign the columns from the row to do it
