### ISSUE TITLE
Convert to RBM theme knockoff

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/theme2016#5]
_From @brashrebel on July 11, 2016 19:27_

_Copied from original issue: Doesn't exist anymore ¯\\__(ツ)\_/¯

**Comment by d4mation** [comment]
As discussed in #1, this is becoming a do-over pretty much.

Progress is on `develop`. Been having some difficulties getting it sorted into a Gulp build to better leverage the newest version of Foundation and then I had to rebase my new repo onto this one to Push the code.

**Comment by brashrebel** [comment]
What's our status here? Ready to deploy to live?

**Comment by d4mation** [comment]
I think it is ready for Live. I've done everything I've wanted with it. The
only thing that really didn't change was the Homepage, but we'd need
more/different content to fix that.

**Comment by brashrebel** [comment]
Let's push it then. I want to review it and open more issues and make some content.

**Comment by d4mation** [comment]
I'll push it out later tonight then :+1:

**Comment by d4mation** [comment]
All live :tada:
