### ISSUE TITLE
Links must change color depending on selected background

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#57]
If we're going to use the unique background color for each download feature, we need to also make sure links change to a visible and clearly actionable color as well. On the Gantt plugin right now, the link to Project Panorama is entirely invisible since it is the same blue as the background. Yikes!

**Comment by joelworsham** [comment]
Schnikees! Probably would be simpler, maybe better, if the links simply were underlined? Rather than colored.

**Comment by brashrebel** [comment]
Not picky here, as long as they are visible.

**Comment by brashrebel** [comment]
Just realized this was never fixed. We really need to. It makes the Gantt product page look pretty bad, and maybe others too. Anyone up for patching it somehow?

**Comment by brashrebel** [comment]
This is better but I think they should still be obviously links. Maybe bring back the underline for them? At this time, there is now way to tell there is a link at all which defeats the purpose of adding one.
