### ISSUE TITLE
Single downloads design

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#6]
I really want to setup the template for single downloads for success. The minimum we need are the standard image, price(s), buy button, description. Let's naturally incorporate all of that stuff at the top and make it look pretty special. Get inspiration from some other plugin and theme sites.

Below that though, I'd like to introduce a few full width sections. These should obviously only display if content exists. They should use our branding colors and alternate probably between solid backgrounds and white or whatever.

- [x] Testimonials. Picturing something on the backend where we can enter a gravatar email of the person being quoted, their name and their quote. We should allow for multiple testimonials on each item but not require a specific number. Probably two columns if there are more than one or something. I don't think it likely that I'll get us more than 4 on a product as that seems a good number.
- [x] Features. I like what they have [here](https://woocommerce.com/products/canvas/) where each feature has an image, title and description. These would be our screenshots with some text. We should allow for any number of these and automatically do that back and forth alignment thing.
- [x] Video. We'll probably just do one single video for most products. This should be in its own section I think.
- [x] Requires. Include a section at the bottom with a multi column bulleted list of requirements.

We can open separate issues to discuss any of these individually.

**Comment by d4mation** [comment]
Since we're using EDD Software Licensing and can/should enter Changelogs, we could add this to the Download Single as well. Not sure if that's the best addition to what is basically a sales page, but I know that's something I like to see personally. :neckbeard:

**Comment by brashrebel** [comment]
Yeah, somewhere we can incorporate a button or link to view changelog. That's fine with me. I like making it easy to find. But it isn't a big sales driver so it needs to be _there_ but not too front and center. And yeah, it should be easy to integrate.

**Comment by d4mation** [comment]
I've decided to put the Changelog within the Documentation Page as it seems to fit better there.

All I need to do for this Issue still is to throw a button to the Documentation Page in there.

**Comment by d4mation** [comment]
Basic Styling/Layout for now. I figure it will evolve/iterate as we get some real content in there.

Here's Download and Documentation Singles (On the Documentation Single, the Side-Nav follows you as you scroll):

![image](https://cloud.githubusercontent.com/assets/7770631/17045059/256c98be-4f94-11e6-8ded-874fd073b739.png)

![image](https://cloud.githubusercontent.com/assets/7770631/17045149/1a5b9226-4f95-11e6-93ed-1d6fea9c404b.png)

**Comment by brashrebel** [comment]
I like this. I think the only thing I'd change at this point is the "features" section of the downloads single background color. That strikes me as a ton of green and that will be a big section. Let's make that one just white background. The video preview can have a colored background, blue or green. I think we should do a white, color, white, color pattern all the way down. Two colors in a row is too much.

Other than that, we can iterate slowly on the rest but it's there so I'm happy.

**Comment by d4mation** [comment]
Now goes Green -> White -> Blue -> White for each section below the standard WooCommerce Content 👍
