### ISSUE TITLE
Add Holler Box

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#61]
Just logging this here for lack of a better place. I'd like to experiment on our site with https://wordpress.org/plugins/holler-box/

I'll get around to adding this soon and see if we can increase our subscribers and customer conversions.

**Comment by BigActual** [comment]
Eric just wrote a plugin for a client site that accomplishes what you're looking for here, I think. Can you elaborate on what you wanted to play with so Eric can oblige your need, please?

**Comment by d4mation** [comment]
If we do _anything_ like this, we need to use a cookie and/or User Meta (if they're logged in) to both store that they've seen this popup before (so that it does not trigger on every page load or if they're returning to the site) as well as not show at all if they've already subscribed.

I get that there is evidence that these things work, but they are pretty horrible. We need to ensure that they don't annoy our customers.

**Comment by d4mation** [comment]
Here's a pretty good article about this. Granted, this is about _popups/modals_ specifically, but this feature sounds functionally the same: Auto-show something on top of everything else to try to force subscription form conversions. Little "faux-chat" panels in the corner can obscure the page and be just as frustrating when they suddenly open as a popup.

https://usabilitygeek.com/pop-ups-vs-usability-conversions-bounce-rates/

**Comment by joelworsham** [comment]
I've used hollar box and actually quite like it. Just my 2 cents.

**Comment by d4mation** [comment]
I'm sure Holler Box as a plugin is well built enough to address my concerns above. 

I just want to ensure we avoid those pitfalls, since @BigActual seems to be leaning toward a custom implementation.

**Comment by joelworsham** [comment]
Yes, agreed.

**Comment by BigActual** [comment]
You two are a bit ahead of me. I like that. I want to know at this point, what Kyle wants to achieve with it. What features or benefits did he want to experiment with?

**Comment by brashrebel** [comment]
I want to improve conversions on our site and this kind of tool is pretty effective. I'd like to use it to show discounts, grow our subscribers, give visitors faster access to information, etc. It has a lot to it.
