### ISSUE TITLE
Some screen sizes cannot see the whole sidebar without scrolling to the very bottom of the page

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/theme2016#81]
On my 1080p monitor I can just barely see the whole thing. But with the built-in display on my laptop I cannot see the Requirements section. 

This will need to be adjusted to always be visible somehow. Whether that is adjusting font-size or finding a way to make the header nav smaller, something will need to be done.

@BigActual thoughts for how to handle this?

![image](https://user-images.githubusercontent.com/7770631/148450703-535420eb-4549-436f-ad5c-070f4f023978.png)

![image](https://user-images.githubusercontent.com/7770631/148450956-20788fcf-08b9-4724-b725-c5b87aff3cb7.png)

![image](https://user-images.githubusercontent.com/7770631/148451020-762cb148-119a-4822-a953-f078c2fffaf0.png)

**Comment by BigActual** [comment]
What does Woocommerce do?

**Comment by d4mation** [comment]
WooCommerce has two key differences:

1. The element isn't sticky. So there is no need to scroll to the very bottom of the page for it to "stop being sticky" and for the bottom of the element to be seen.
2. WooCommerce doesn't default to any of the accordions being open. But I think we should keep this one expanded personally.

**Comment by BigActual** [comment]
Do we need to keep it sticky?

**Comment by d4mation** [comment]
Nope. It is cool, but not at the expense of core functionality. I'm looking into how to remove that now.

**Comment by BigActual** [comment]
Can we make it sticky only on large monitors?

**Comment by d4mation** [comment]
Not exactly.

Our main issue here is that the height of that sidebar is fluid. Depending on its content or what sections are open, it can be larger or shorter.

We could write some JS so that this feature only enables if the screen is X wide _and_ Y tall, but due to the other variables at play I'm not sure how reliable doing so will truly be.

I figure the main thing you want is a "buy" button to follow the user. What if, once the sidebar is off-screen (or all the time on mobile) a different element would appear that _is_ sticky that only contains the "buy" information? Perhaps stuck to the bottom of the screen? This would be the toggles for the different price types as well as the button itself.
